version: '3.4'
services:
  frontend:
    image: frontend
    container_name: frontend
    restart: always
    command: yarn start
    ports:
      - "3000:3000"
    build: ./frontend
  backend:
    image: backend
    container_name: backend
    command: yarn dev
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: db_user
      MONGODB_PASSWORD: QAZwsx123
      MONGO_DB: myFirstDatabase
    volumes:
      - ./data-node:/data/db
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge